name = "Miniseason Summer 2026 Modpack"
author = "TheDeathlyCow"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "492e9df5bb19d44de34da804f4e3d53ed4b096b49e95674d9ab5bdf7e45daadc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/openloader/packs/"
