name = "Miniseason Summer 2026 Modpack"
author = "TheDeathlyCow"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93467e3124d6971d23022aeebabcb71078e23af3b98d0a327f835b9261534b2e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/openloader/packs/"
