name = "Miniseason Summer 2026 Modpack"
author = "TheDeathlyCow"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a3d85cf7b30e8d3860e5073e93c1b3ab6169dc2d495e9db855de39a96352b96"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/openloader/packs/"
